# Generated by Django 3.0.3 on 2020-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0006_auto_20200422_2212'),
        ('Profile', '0002_auto_20200422_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prodouct',
            field=models.ManyToManyField(to='Index.Order_product'),
        ),
    ]
