# Generated by Django 3.0.3 on 2020-04-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_order_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prodouct',
            new_name='prodoucts',
        ),
    ]
