# Generated by Django 3.0.3 on 2020-04-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20200422_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
