# Generated by Django 3.0.3 on 2020-04-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_remove_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
