# Generated by Django 3.0.3 on 2020-04-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0015_auto_20200423_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0007_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('delivery_place', models.TextField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NS', 'Notyetshipped'), ('S', 'Shipping'), ('D', 'Delivered')], max_length=2)),
                ('prodoucts', models.ManyToManyField(to='Index.Order_product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
