# Generated by Django 3.0.3 on 2020-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0016_auto_20200423_1412'),
        ('Profile', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prodoucts',
            field=models.ManyToManyField(to='Index.Order_products'),
        ),
    ]
