# Generated by Django 3.0.3 on 2020-04-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promtion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Promotion'),
        ),
    ]
