# Generated by Django 3.0.3 on 2020-04-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_order_promtion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promtion_id',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
