# Generated by Django 3.0.3 on 2020-04-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_auto_20200423_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
