# Generated by Django 3.0.3 on 2020-04-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0008_promotion'),
        ('Profile', '0010_auto_20200425_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promtion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Index.Promotion'),
        ),
    ]
