# Generated by Django 3.0.3 on 2020-04-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prodoucts',
            new_name='products',
        ),
    ]
