# Generated by Django 3.0.3 on 2020-04-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_order_promtion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='promtion_id',
            new_name='promotion_id',
        ),
    ]
