# Generated by Django 3.0.3 on 2020-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_auto_20200425_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NS', 'Packaging'), ('D', 'Delivering'), ('R', 'Received'), ('Re', 'Refunde')], max_length=2),
        ),
    ]
