# Generated by Django 3.0.3 on 2020-04-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_auto_20200424_1505'),
        ('Profile', '0002_auto_20200424_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Index.Address'),
        ),
    ]
