# Generated by Django 3.0.3 on 2020-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_url',
            field=models.ImageField(default='somting.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product_picture',
        ),
    ]
