# Generated by Django 3.0.3 on 2020-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20200420_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
