# Generated by Django 3.0.3 on 2020-04-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_product_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
