# Generated by Django 3.0.3 on 2020-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0006_auto_20200422_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
