# Generated by Django 3.0.3 on 2020-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_auto_20200424_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
