# Generated by Django 3.0.3 on 2020-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0008_auto_20200422_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
