# Generated by Django 3.0.3 on 2020-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0009_auto_20200422_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='unit_price',
        ),
    ]
