# Generated by Django 3.0.3 on 2020-04-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0010_remove_order_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
