# Generated by Django 3.0.3 on 2020-04-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0012_order_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_product',
            old_name='unit',
            new_name='quantity',
        ),
    ]
