# Generated by Django 3.0.3 on 2020-04-23 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Index', '0013_auto_20200423_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
     
    ]
