# Generated by Django 3.0.3 on 2020-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0014_auto_20200423_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='order_no',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
