# Generated by Django 3.0.3 on 2020-04-23 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Index', '0016_auto_20200423_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_products',
            old_name='quantity',
            new_name='unit',
        ),
        
    ]
