# Generated by Django 3.0.3 on 2020-04-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0017_auto_20200423_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_products',
            old_name='unit',
            new_name='quantity',
        ),
    ]
