# Generated by Django 3.0.3 on 2020-04-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_type',
            name='slug',
        ),
    ]
