# Generated by Django 3.0.3 on 2020-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_auto_20200424_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
